### ISSUE TITLE
There occurs an error when trying to run the app because of a missing settings.json file

### ISSUE THREAD

**Issue by MariettaB** [danielmarcu/ISI-CWIC#1]
Warning: The --production flag should only be used to simulate production
bundling for testing purposes. Use meteor build to create a bundle for
production deployment. See: https://guide.meteor.com/deployment.html
[[[[[ ~/ISI-CWIC/bwapp2 ]]]]]

=> Started proxy.
[BABEL] Note: The code generator has deoptimised the styling of "/client/vendor/bower_components/angular-animate/angular-animate.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/client/vendor/bower_components/angular-translate/angular-translate.js" as it exceeds the max of "100KB".
=> Errors prevented startup:
   
   While preparing to run:
   settings.json: file not found (settings file)
   
=> Your application has errors. Waiting for file change.

**Comment by wwhavoc** [comment]
Hi

The settings.json file is a file you create that can contain:
{
}

We are using the settings for some testing code.   Or remove it from the resquiremnets to start the app.  Since deployment and development is one in the same for this project, there is no need to worry about using meteor build to create the deployment package.

**Comment by wwhavoc** [comment]
Hi

Looks like I need to update the app to make things more flexible.  Be back with an update.

**Comment by wwhavoc** [comment]
Hi

Creating the settings.json will require the creation of an aws account.  This is used to create experiments on mturk as well as storing images and videos from command experiements.
Please review [AWS MTurk Setup](https://github.com/danielmarcu/ISI-CWIC#aws-and-mechanical-turk)

**Comment by MariettaB** [comment]
Hi and thank you for your answer. Unfortunately as far as I can see one needs to be a resident of the United States to sign up for a Mechanical Turk requester account. Is there another solution without using Mechanical Turk?

**Comment by wwhavoc** [comment]
Hi,

Unfortunately the application is closely linked to Turker jobs and S3 buckets.
